/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTransfersRouteImport } from './routes/_authenticated/transfers'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedDistributionRouteImport } from './routes/_authenticated/distribution'
import { Route as AuthenticatedCostsRouteImport } from './routes/_authenticated/costs'
import { Route as AuthenticatedBranchRequestsRouteImport } from './routes/_authenticated/branch-requests'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedShipmentsIndexRouteImport } from './routes/_authenticated/shipments/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedShipmentsNewRouteImport } from './routes/_authenticated/shipments/new'
import { Route as AuthenticatedShipmentsIdRouteImport } from './routes/_authenticated/shipments/$id'
import { Route as AuthenticatedDistributionShipmentIdRouteImport } from './routes/_authenticated/distribution/$shipmentId'
import { Route as AuthenticatedDashboardSuperAdminRouteImport } from './routes/_authenticated/dashboard/super-admin'
import { Route as AuthenticatedDashboardManagerRouteImport } from './routes/_authenticated/dashboard/manager'
import { Route as AuthenticatedDashboardBranchRouteImport } from './routes/_authenticated/dashboard/branch'
import { Route as AuthenticatedDashboardAdminRouteImport } from './routes/_authenticated/dashboard/admin'
import { Route as AuthenticatedAdminSuppliersRouteImport } from './routes/_authenticated/admin/suppliers'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin/products'
import { Route as AuthenticatedAdminManagersRouteImport } from './routes/_authenticated/admin/managers'
import { Route as AuthenticatedAdminBranchesRouteImport } from './routes/_authenticated/admin/branches'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTransfersRoute = AuthenticatedTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDistributionRoute =
  AuthenticatedDistributionRouteImport.update({
    id: '/distribution',
    path: '/distribution',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCostsRoute = AuthenticatedCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBranchRequestsRoute =
  AuthenticatedBranchRequestsRouteImport.update({
    id: '/branch-requests',
    path: '/branch-requests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShipmentsIndexRoute =
  AuthenticatedShipmentsIndexRouteImport.update({
    id: '/shipments/',
    path: '/shipments/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedShipmentsNewRoute =
  AuthenticatedShipmentsNewRouteImport.update({
    id: '/shipments/new',
    path: '/shipments/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedShipmentsIdRoute =
  AuthenticatedShipmentsIdRouteImport.update({
    id: '/shipments/$id',
    path: '/shipments/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDistributionShipmentIdRoute =
  AuthenticatedDistributionShipmentIdRouteImport.update({
    id: '/$shipmentId',
    path: '/$shipmentId',
    getParentRoute: () => AuthenticatedDistributionRoute,
  } as any)
const AuthenticatedDashboardSuperAdminRoute =
  AuthenticatedDashboardSuperAdminRouteImport.update({
    id: '/dashboard/super-admin',
    path: '/dashboard/super-admin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardManagerRoute =
  AuthenticatedDashboardManagerRouteImport.update({
    id: '/dashboard/manager',
    path: '/dashboard/manager',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardBranchRoute =
  AuthenticatedDashboardBranchRouteImport.update({
    id: '/dashboard/branch',
    path: '/dashboard/branch',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardAdminRoute =
  AuthenticatedDashboardAdminRouteImport.update({
    id: '/dashboard/admin',
    path: '/dashboard/admin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSuppliersRoute =
  AuthenticatedAdminSuppliersRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminManagersRoute =
  AuthenticatedAdminManagersRouteImport.update({
    id: '/managers',
    path: '/managers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBranchesRoute =
  AuthenticatedAdminBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/branch-requests': typeof AuthenticatedBranchRequestsRoute
  '/costs': typeof AuthenticatedCostsRoute
  '/distribution': typeof AuthenticatedDistributionRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/transfers': typeof AuthenticatedTransfersRoute
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/managers': typeof AuthenticatedAdminManagersRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/suppliers': typeof AuthenticatedAdminSuppliersRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/branch': typeof AuthenticatedDashboardBranchRoute
  '/dashboard/manager': typeof AuthenticatedDashboardManagerRoute
  '/dashboard/super-admin': typeof AuthenticatedDashboardSuperAdminRoute
  '/distribution/$shipmentId': typeof AuthenticatedDistributionShipmentIdRoute
  '/shipments/$id': typeof AuthenticatedShipmentsIdRoute
  '/shipments/new': typeof AuthenticatedShipmentsNewRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/shipments/': typeof AuthenticatedShipmentsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/branch-requests': typeof AuthenticatedBranchRequestsRoute
  '/costs': typeof AuthenticatedCostsRoute
  '/distribution': typeof AuthenticatedDistributionRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/transfers': typeof AuthenticatedTransfersRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/managers': typeof AuthenticatedAdminManagersRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/suppliers': typeof AuthenticatedAdminSuppliersRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/branch': typeof AuthenticatedDashboardBranchRoute
  '/dashboard/manager': typeof AuthenticatedDashboardManagerRoute
  '/dashboard/super-admin': typeof AuthenticatedDashboardSuperAdminRoute
  '/distribution/$shipmentId': typeof AuthenticatedDistributionShipmentIdRoute
  '/shipments/$id': typeof AuthenticatedShipmentsIdRoute
  '/shipments/new': typeof AuthenticatedShipmentsNewRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/shipments': typeof AuthenticatedShipmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/branch-requests': typeof AuthenticatedBranchRequestsRoute
  '/_authenticated/costs': typeof AuthenticatedCostsRoute
  '/_authenticated/distribution': typeof AuthenticatedDistributionRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/_authenticated/transfers': typeof AuthenticatedTransfersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/_authenticated/admin/managers': typeof AuthenticatedAdminManagersRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/suppliers': typeof AuthenticatedAdminSuppliersRoute
  '/_authenticated/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/_authenticated/dashboard/branch': typeof AuthenticatedDashboardBranchRoute
  '/_authenticated/dashboard/manager': typeof AuthenticatedDashboardManagerRoute
  '/_authenticated/dashboard/super-admin': typeof AuthenticatedDashboardSuperAdminRoute
  '/_authenticated/distribution/$shipmentId': typeof AuthenticatedDistributionShipmentIdRoute
  '/_authenticated/shipments/$id': typeof AuthenticatedShipmentsIdRoute
  '/_authenticated/shipments/new': typeof AuthenticatedShipmentsNewRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/shipments/': typeof AuthenticatedShipmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/analytics'
    | '/branch-requests'
    | '/costs'
    | '/distribution'
    | '/notifications'
    | '/settings'
    | '/suppliers'
    | '/transfers'
    | '/admin/branches'
    | '/admin/managers'
    | '/admin/products'
    | '/admin/suppliers'
    | '/dashboard/admin'
    | '/dashboard/branch'
    | '/dashboard/manager'
    | '/dashboard/super-admin'
    | '/distribution/$shipmentId'
    | '/shipments/$id'
    | '/shipments/new'
    | '/admin/'
    | '/shipments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/analytics'
    | '/branch-requests'
    | '/costs'
    | '/distribution'
    | '/notifications'
    | '/settings'
    | '/suppliers'
    | '/transfers'
    | '/'
    | '/admin/branches'
    | '/admin/managers'
    | '/admin/products'
    | '/admin/suppliers'
    | '/dashboard/admin'
    | '/dashboard/branch'
    | '/dashboard/manager'
    | '/dashboard/super-admin'
    | '/distribution/$shipmentId'
    | '/shipments/$id'
    | '/shipments/new'
    | '/admin'
    | '/shipments'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/analytics'
    | '/_authenticated/branch-requests'
    | '/_authenticated/costs'
    | '/_authenticated/distribution'
    | '/_authenticated/notifications'
    | '/_authenticated/settings'
    | '/_authenticated/suppliers'
    | '/_authenticated/transfers'
    | '/_authenticated/'
    | '/_authenticated/admin/branches'
    | '/_authenticated/admin/managers'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/suppliers'
    | '/_authenticated/dashboard/admin'
    | '/_authenticated/dashboard/branch'
    | '/_authenticated/dashboard/manager'
    | '/_authenticated/dashboard/super-admin'
    | '/_authenticated/distribution/$shipmentId'
    | '/_authenticated/shipments/$id'
    | '/_authenticated/shipments/new'
    | '/_authenticated/admin/'
    | '/_authenticated/shipments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transfers': {
      id: '/_authenticated/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AuthenticatedTransfersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/distribution': {
      id: '/_authenticated/distribution'
      path: '/distribution'
      fullPath: '/distribution'
      preLoaderRoute: typeof AuthenticatedDistributionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/costs': {
      id: '/_authenticated/costs'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof AuthenticatedCostsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/branch-requests': {
      id: '/_authenticated/branch-requests'
      path: '/branch-requests'
      fullPath: '/branch-requests'
      preLoaderRoute: typeof AuthenticatedBranchRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shipments/': {
      id: '/_authenticated/shipments/'
      path: '/shipments'
      fullPath: '/shipments/'
      preLoaderRoute: typeof AuthenticatedShipmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/shipments/new': {
      id: '/_authenticated/shipments/new'
      path: '/shipments/new'
      fullPath: '/shipments/new'
      preLoaderRoute: typeof AuthenticatedShipmentsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shipments/$id': {
      id: '/_authenticated/shipments/$id'
      path: '/shipments/$id'
      fullPath: '/shipments/$id'
      preLoaderRoute: typeof AuthenticatedShipmentsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/distribution/$shipmentId': {
      id: '/_authenticated/distribution/$shipmentId'
      path: '/$shipmentId'
      fullPath: '/distribution/$shipmentId'
      preLoaderRoute: typeof AuthenticatedDistributionShipmentIdRouteImport
      parentRoute: typeof AuthenticatedDistributionRoute
    }
    '/_authenticated/dashboard/super-admin': {
      id: '/_authenticated/dashboard/super-admin'
      path: '/dashboard/super-admin'
      fullPath: '/dashboard/super-admin'
      preLoaderRoute: typeof AuthenticatedDashboardSuperAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/manager': {
      id: '/_authenticated/dashboard/manager'
      path: '/dashboard/manager'
      fullPath: '/dashboard/manager'
      preLoaderRoute: typeof AuthenticatedDashboardManagerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/branch': {
      id: '/_authenticated/dashboard/branch'
      path: '/dashboard/branch'
      fullPath: '/dashboard/branch'
      preLoaderRoute: typeof AuthenticatedDashboardBranchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/admin': {
      id: '/_authenticated/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AuthenticatedDashboardAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/suppliers': {
      id: '/_authenticated/admin/suppliers'
      path: '/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AuthenticatedAdminSuppliersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/managers': {
      id: '/_authenticated/admin/managers'
      path: '/managers'
      fullPath: '/admin/managers'
      preLoaderRoute: typeof AuthenticatedAdminManagersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/branches': {
      id: '/_authenticated/admin/branches'
      path: '/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AuthenticatedAdminBranchesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBranchesRoute: typeof AuthenticatedAdminBranchesRoute
  AuthenticatedAdminManagersRoute: typeof AuthenticatedAdminManagersRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminSuppliersRoute: typeof AuthenticatedAdminSuppliersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBranchesRoute: AuthenticatedAdminBranchesRoute,
  AuthenticatedAdminManagersRoute: AuthenticatedAdminManagersRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminSuppliersRoute: AuthenticatedAdminSuppliersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDistributionRouteChildren {
  AuthenticatedDistributionShipmentIdRoute: typeof AuthenticatedDistributionShipmentIdRoute
}

const AuthenticatedDistributionRouteChildren: AuthenticatedDistributionRouteChildren =
  {
    AuthenticatedDistributionShipmentIdRoute:
      AuthenticatedDistributionShipmentIdRoute,
  }

const AuthenticatedDistributionRouteWithChildren =
  AuthenticatedDistributionRoute._addFileChildren(
    AuthenticatedDistributionRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBranchRequestsRoute: typeof AuthenticatedBranchRequestsRoute
  AuthenticatedCostsRoute: typeof AuthenticatedCostsRoute
  AuthenticatedDistributionRoute: typeof AuthenticatedDistributionRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
  AuthenticatedTransfersRoute: typeof AuthenticatedTransfersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDashboardAdminRoute: typeof AuthenticatedDashboardAdminRoute
  AuthenticatedDashboardBranchRoute: typeof AuthenticatedDashboardBranchRoute
  AuthenticatedDashboardManagerRoute: typeof AuthenticatedDashboardManagerRoute
  AuthenticatedDashboardSuperAdminRoute: typeof AuthenticatedDashboardSuperAdminRoute
  AuthenticatedShipmentsIdRoute: typeof AuthenticatedShipmentsIdRoute
  AuthenticatedShipmentsNewRoute: typeof AuthenticatedShipmentsNewRoute
  AuthenticatedShipmentsIndexRoute: typeof AuthenticatedShipmentsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBranchRequestsRoute: AuthenticatedBranchRequestsRoute,
  AuthenticatedCostsRoute: AuthenticatedCostsRoute,
  AuthenticatedDistributionRoute: AuthenticatedDistributionRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
  AuthenticatedTransfersRoute: AuthenticatedTransfersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDashboardAdminRoute: AuthenticatedDashboardAdminRoute,
  AuthenticatedDashboardBranchRoute: AuthenticatedDashboardBranchRoute,
  AuthenticatedDashboardManagerRoute: AuthenticatedDashboardManagerRoute,
  AuthenticatedDashboardSuperAdminRoute: AuthenticatedDashboardSuperAdminRoute,
  AuthenticatedShipmentsIdRoute: AuthenticatedShipmentsIdRoute,
  AuthenticatedShipmentsNewRoute: AuthenticatedShipmentsNewRoute,
  AuthenticatedShipmentsIndexRoute: AuthenticatedShipmentsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
