/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTransfersRouteImport } from './routes/_authenticated/transfers'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedSuperAdminRouteImport } from './routes/_authenticated/super-admin'
import { Route as AuthenticatedStatisticsRouteImport } from './routes/_authenticated/statistics'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOffersRouteImport } from './routes/_authenticated/offers'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMasterDataRouteImport } from './routes/_authenticated/master-data'
import { Route as AuthenticatedManagerOffersRouteImport } from './routes/_authenticated/manager-offers'
import { Route as AuthenticatedDistributionRouteImport } from './routes/_authenticated/distribution'
import { Route as AuthenticatedCostsRouteImport } from './routes/_authenticated/costs'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedBranchRequestsRouteImport } from './routes/_authenticated/branch-requests'
import { Route as AuthenticatedBranchOffersRouteImport } from './routes/_authenticated/branch-offers'
import { Route as AuthenticatedBranchCalendarRouteImport } from './routes/_authenticated/branch-calendar'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSuperAdminIndexRouteImport } from './routes/_authenticated/super-admin/index'
import { Route as AuthenticatedShipmentsIndexRouteImport } from './routes/_authenticated/shipments/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedSuperAdminUsersRouteImport } from './routes/_authenticated/super-admin/users'
import { Route as AuthenticatedSuperAdminLogsRouteImport } from './routes/_authenticated/super-admin/logs'
import { Route as AuthenticatedShipmentsNewRouteImport } from './routes/_authenticated/shipments/new'
import { Route as AuthenticatedShipmentsIdRouteImport } from './routes/_authenticated/shipments/$id'
import { Route as AuthenticatedDistributionShipmentIdRouteImport } from './routes/_authenticated/distribution/$shipmentId'
import { Route as AuthenticatedDashboardSuperAdminRouteImport } from './routes/_authenticated/dashboard/super-admin'
import { Route as AuthenticatedDashboardManagerRouteImport } from './routes/_authenticated/dashboard/manager'
import { Route as AuthenticatedDashboardBranchRouteImport } from './routes/_authenticated/dashboard/branch'
import { Route as AuthenticatedDashboardAdminRouteImport } from './routes/_authenticated/dashboard/admin'
import { Route as AuthenticatedAdminVacationsRouteImport } from './routes/_authenticated/admin/vacations'
import { Route as AuthenticatedAdminTriggersRouteImport } from './routes/_authenticated/admin/triggers'
import { Route as AuthenticatedAdminSuppliersRouteImport } from './routes/_authenticated/admin/suppliers'
import { Route as AuthenticatedAdminQaRouteImport } from './routes/_authenticated/admin/qa'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin/products'
import { Route as AuthenticatedAdminManagersRouteImport } from './routes/_authenticated/admin/managers'
import { Route as AuthenticatedAdminLoadingPlanRouteImport } from './routes/_authenticated/admin/loading-plan'
import { Route as AuthenticatedAdminCustomsRouteImport } from './routes/_authenticated/admin/customs'
import { Route as AuthenticatedAdminCountriesMasterRouteImport } from './routes/_authenticated/admin/countries-master'
import { Route as AuthenticatedAdminCountriesRouteImport } from './routes/_authenticated/admin/countries'
import { Route as AuthenticatedAdminBranchesRouteImport } from './routes/_authenticated/admin/branches'
import { Route as ApiPublicHooksRefreshFxRouteImport } from './routes/api/public/hooks/refresh-fx'
import { Route as AuthenticatedShipmentsIdProductsRouteImport } from './routes/_authenticated/shipments/$id.products'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTransfersRoute = AuthenticatedTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuperAdminRoute = AuthenticatedSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStatisticsRoute = AuthenticatedStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOffersRoute = AuthenticatedOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMasterDataRoute = AuthenticatedMasterDataRouteImport.update({
  id: '/master-data',
  path: '/master-data',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedManagerOffersRoute =
  AuthenticatedManagerOffersRouteImport.update({
    id: '/manager-offers',
    path: '/manager-offers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDistributionRoute =
  AuthenticatedDistributionRouteImport.update({
    id: '/distribution',
    path: '/distribution',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCostsRoute = AuthenticatedCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBranchRequestsRoute =
  AuthenticatedBranchRequestsRouteImport.update({
    id: '/branch-requests',
    path: '/branch-requests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBranchOffersRoute =
  AuthenticatedBranchOffersRouteImport.update({
    id: '/branch-offers',
    path: '/branch-offers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBranchCalendarRoute =
  AuthenticatedBranchCalendarRouteImport.update({
    id: '/branch-calendar',
    path: '/branch-calendar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuperAdminIndexRoute =
  AuthenticatedSuperAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedShipmentsIndexRoute =
  AuthenticatedShipmentsIndexRouteImport.update({
    id: '/shipments/',
    path: '/shipments/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedSuperAdminUsersRoute =
  AuthenticatedSuperAdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminLogsRoute =
  AuthenticatedSuperAdminLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedShipmentsNewRoute =
  AuthenticatedShipmentsNewRouteImport.update({
    id: '/shipments/new',
    path: '/shipments/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedShipmentsIdRoute =
  AuthenticatedShipmentsIdRouteImport.update({
    id: '/shipments/$id',
    path: '/shipments/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDistributionShipmentIdRoute =
  AuthenticatedDistributionShipmentIdRouteImport.update({
    id: '/$shipmentId',
    path: '/$shipmentId',
    getParentRoute: () => AuthenticatedDistributionRoute,
  } as any)
const AuthenticatedDashboardSuperAdminRoute =
  AuthenticatedDashboardSuperAdminRouteImport.update({
    id: '/dashboard/super-admin',
    path: '/dashboard/super-admin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardManagerRoute =
  AuthenticatedDashboardManagerRouteImport.update({
    id: '/dashboard/manager',
    path: '/dashboard/manager',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardBranchRoute =
  AuthenticatedDashboardBranchRouteImport.update({
    id: '/dashboard/branch',
    path: '/dashboard/branch',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardAdminRoute =
  AuthenticatedDashboardAdminRouteImport.update({
    id: '/dashboard/admin',
    path: '/dashboard/admin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminVacationsRoute =
  AuthenticatedAdminVacationsRouteImport.update({
    id: '/vacations',
    path: '/vacations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTriggersRoute =
  AuthenticatedAdminTriggersRouteImport.update({
    id: '/triggers',
    path: '/triggers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSuppliersRoute =
  AuthenticatedAdminSuppliersRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminQaRoute = AuthenticatedAdminQaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminManagersRoute =
  AuthenticatedAdminManagersRouteImport.update({
    id: '/managers',
    path: '/managers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLoadingPlanRoute =
  AuthenticatedAdminLoadingPlanRouteImport.update({
    id: '/loading-plan',
    path: '/loading-plan',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomsRoute =
  AuthenticatedAdminCustomsRouteImport.update({
    id: '/customs',
    path: '/customs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCountriesMasterRoute =
  AuthenticatedAdminCountriesMasterRouteImport.update({
    id: '/countries-master',
    path: '/countries-master',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCountriesRoute =
  AuthenticatedAdminCountriesRouteImport.update({
    id: '/countries',
    path: '/countries',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBranchesRoute =
  AuthenticatedAdminBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicHooksRefreshFxRoute = ApiPublicHooksRefreshFxRouteImport.update({
  id: '/api/public/hooks/refresh-fx',
  path: '/api/public/hooks/refresh-fx',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedShipmentsIdProductsRoute =
  AuthenticatedShipmentsIdProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedShipmentsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/branch-calendar': typeof AuthenticatedBranchCalendarRoute
  '/branch-offers': typeof AuthenticatedBranchOffersRoute
  '/branch-requests': typeof AuthenticatedBranchRequestsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/costs': typeof AuthenticatedCostsRoute
  '/distribution': typeof AuthenticatedDistributionRouteWithChildren
  '/manager-offers': typeof AuthenticatedManagerOffersRoute
  '/master-data': typeof AuthenticatedMasterDataRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/offers': typeof AuthenticatedOffersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/statistics': typeof AuthenticatedStatisticsRoute
  '/super-admin': typeof AuthenticatedSuperAdminRouteWithChildren
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/transfers': typeof AuthenticatedTransfersRoute
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/countries': typeof AuthenticatedAdminCountriesRoute
  '/admin/countries-master': typeof AuthenticatedAdminCountriesMasterRoute
  '/admin/customs': typeof AuthenticatedAdminCustomsRoute
  '/admin/loading-plan': typeof AuthenticatedAdminLoadingPlanRoute
  '/admin/managers': typeof AuthenticatedAdminManagersRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/qa': typeof AuthenticatedAdminQaRoute
  '/admin/suppliers': typeof AuthenticatedAdminSuppliersRoute
  '/admin/triggers': typeof AuthenticatedAdminTriggersRoute
  '/admin/vacations': typeof AuthenticatedAdminVacationsRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/branch': typeof AuthenticatedDashboardBranchRoute
  '/dashboard/manager': typeof AuthenticatedDashboardManagerRoute
  '/dashboard/super-admin': typeof AuthenticatedDashboardSuperAdminRoute
  '/distribution/$shipmentId': typeof AuthenticatedDistributionShipmentIdRoute
  '/shipments/$id': typeof AuthenticatedShipmentsIdRouteWithChildren
  '/shipments/new': typeof AuthenticatedShipmentsNewRoute
  '/super-admin/logs': typeof AuthenticatedSuperAdminLogsRoute
  '/super-admin/users': typeof AuthenticatedSuperAdminUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/shipments/': typeof AuthenticatedShipmentsIndexRoute
  '/super-admin/': typeof AuthenticatedSuperAdminIndexRoute
  '/shipments/$id/products': typeof AuthenticatedShipmentsIdProductsRoute
  '/api/public/hooks/refresh-fx': typeof ApiPublicHooksRefreshFxRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/branch-calendar': typeof AuthenticatedBranchCalendarRoute
  '/branch-offers': typeof AuthenticatedBranchOffersRoute
  '/branch-requests': typeof AuthenticatedBranchRequestsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/costs': typeof AuthenticatedCostsRoute
  '/distribution': typeof AuthenticatedDistributionRouteWithChildren
  '/manager-offers': typeof AuthenticatedManagerOffersRoute
  '/master-data': typeof AuthenticatedMasterDataRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/offers': typeof AuthenticatedOffersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/statistics': typeof AuthenticatedStatisticsRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/transfers': typeof AuthenticatedTransfersRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/countries': typeof AuthenticatedAdminCountriesRoute
  '/admin/countries-master': typeof AuthenticatedAdminCountriesMasterRoute
  '/admin/customs': typeof AuthenticatedAdminCustomsRoute
  '/admin/loading-plan': typeof AuthenticatedAdminLoadingPlanRoute
  '/admin/managers': typeof AuthenticatedAdminManagersRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/qa': typeof AuthenticatedAdminQaRoute
  '/admin/suppliers': typeof AuthenticatedAdminSuppliersRoute
  '/admin/triggers': typeof AuthenticatedAdminTriggersRoute
  '/admin/vacations': typeof AuthenticatedAdminVacationsRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/branch': typeof AuthenticatedDashboardBranchRoute
  '/dashboard/manager': typeof AuthenticatedDashboardManagerRoute
  '/dashboard/super-admin': typeof AuthenticatedDashboardSuperAdminRoute
  '/distribution/$shipmentId': typeof AuthenticatedDistributionShipmentIdRoute
  '/shipments/$id': typeof AuthenticatedShipmentsIdRouteWithChildren
  '/shipments/new': typeof AuthenticatedShipmentsNewRoute
  '/super-admin/logs': typeof AuthenticatedSuperAdminLogsRoute
  '/super-admin/users': typeof AuthenticatedSuperAdminUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/shipments': typeof AuthenticatedShipmentsIndexRoute
  '/super-admin': typeof AuthenticatedSuperAdminIndexRoute
  '/shipments/$id/products': typeof AuthenticatedShipmentsIdProductsRoute
  '/api/public/hooks/refresh-fx': typeof ApiPublicHooksRefreshFxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/branch-calendar': typeof AuthenticatedBranchCalendarRoute
  '/_authenticated/branch-offers': typeof AuthenticatedBranchOffersRoute
  '/_authenticated/branch-requests': typeof AuthenticatedBranchRequestsRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/costs': typeof AuthenticatedCostsRoute
  '/_authenticated/distribution': typeof AuthenticatedDistributionRouteWithChildren
  '/_authenticated/manager-offers': typeof AuthenticatedManagerOffersRoute
  '/_authenticated/master-data': typeof AuthenticatedMasterDataRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/offers': typeof AuthenticatedOffersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/statistics': typeof AuthenticatedStatisticsRoute
  '/_authenticated/super-admin': typeof AuthenticatedSuperAdminRouteWithChildren
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/_authenticated/transfers': typeof AuthenticatedTransfersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/_authenticated/admin/countries': typeof AuthenticatedAdminCountriesRoute
  '/_authenticated/admin/countries-master': typeof AuthenticatedAdminCountriesMasterRoute
  '/_authenticated/admin/customs': typeof AuthenticatedAdminCustomsRoute
  '/_authenticated/admin/loading-plan': typeof AuthenticatedAdminLoadingPlanRoute
  '/_authenticated/admin/managers': typeof AuthenticatedAdminManagersRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/qa': typeof AuthenticatedAdminQaRoute
  '/_authenticated/admin/suppliers': typeof AuthenticatedAdminSuppliersRoute
  '/_authenticated/admin/triggers': typeof AuthenticatedAdminTriggersRoute
  '/_authenticated/admin/vacations': typeof AuthenticatedAdminVacationsRoute
  '/_authenticated/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/_authenticated/dashboard/branch': typeof AuthenticatedDashboardBranchRoute
  '/_authenticated/dashboard/manager': typeof AuthenticatedDashboardManagerRoute
  '/_authenticated/dashboard/super-admin': typeof AuthenticatedDashboardSuperAdminRoute
  '/_authenticated/distribution/$shipmentId': typeof AuthenticatedDistributionShipmentIdRoute
  '/_authenticated/shipments/$id': typeof AuthenticatedShipmentsIdRouteWithChildren
  '/_authenticated/shipments/new': typeof AuthenticatedShipmentsNewRoute
  '/_authenticated/super-admin/logs': typeof AuthenticatedSuperAdminLogsRoute
  '/_authenticated/super-admin/users': typeof AuthenticatedSuperAdminUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/shipments/': typeof AuthenticatedShipmentsIndexRoute
  '/_authenticated/super-admin/': typeof AuthenticatedSuperAdminIndexRoute
  '/_authenticated/shipments/$id/products': typeof AuthenticatedShipmentsIdProductsRoute
  '/api/public/hooks/refresh-fx': typeof ApiPublicHooksRefreshFxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/analytics'
    | '/branch-calendar'
    | '/branch-offers'
    | '/branch-requests'
    | '/calendar'
    | '/costs'
    | '/distribution'
    | '/manager-offers'
    | '/master-data'
    | '/notifications'
    | '/offers'
    | '/settings'
    | '/statistics'
    | '/super-admin'
    | '/suppliers'
    | '/transfers'
    | '/admin/branches'
    | '/admin/countries'
    | '/admin/countries-master'
    | '/admin/customs'
    | '/admin/loading-plan'
    | '/admin/managers'
    | '/admin/products'
    | '/admin/qa'
    | '/admin/suppliers'
    | '/admin/triggers'
    | '/admin/vacations'
    | '/dashboard/admin'
    | '/dashboard/branch'
    | '/dashboard/manager'
    | '/dashboard/super-admin'
    | '/distribution/$shipmentId'
    | '/shipments/$id'
    | '/shipments/new'
    | '/super-admin/logs'
    | '/super-admin/users'
    | '/admin/'
    | '/shipments/'
    | '/super-admin/'
    | '/shipments/$id/products'
    | '/api/public/hooks/refresh-fx'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/analytics'
    | '/branch-calendar'
    | '/branch-offers'
    | '/branch-requests'
    | '/calendar'
    | '/costs'
    | '/distribution'
    | '/manager-offers'
    | '/master-data'
    | '/notifications'
    | '/offers'
    | '/settings'
    | '/statistics'
    | '/suppliers'
    | '/transfers'
    | '/'
    | '/admin/branches'
    | '/admin/countries'
    | '/admin/countries-master'
    | '/admin/customs'
    | '/admin/loading-plan'
    | '/admin/managers'
    | '/admin/products'
    | '/admin/qa'
    | '/admin/suppliers'
    | '/admin/triggers'
    | '/admin/vacations'
    | '/dashboard/admin'
    | '/dashboard/branch'
    | '/dashboard/manager'
    | '/dashboard/super-admin'
    | '/distribution/$shipmentId'
    | '/shipments/$id'
    | '/shipments/new'
    | '/super-admin/logs'
    | '/super-admin/users'
    | '/admin'
    | '/shipments'
    | '/super-admin'
    | '/shipments/$id/products'
    | '/api/public/hooks/refresh-fx'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/analytics'
    | '/_authenticated/branch-calendar'
    | '/_authenticated/branch-offers'
    | '/_authenticated/branch-requests'
    | '/_authenticated/calendar'
    | '/_authenticated/costs'
    | '/_authenticated/distribution'
    | '/_authenticated/manager-offers'
    | '/_authenticated/master-data'
    | '/_authenticated/notifications'
    | '/_authenticated/offers'
    | '/_authenticated/settings'
    | '/_authenticated/statistics'
    | '/_authenticated/super-admin'
    | '/_authenticated/suppliers'
    | '/_authenticated/transfers'
    | '/_authenticated/'
    | '/_authenticated/admin/branches'
    | '/_authenticated/admin/countries'
    | '/_authenticated/admin/countries-master'
    | '/_authenticated/admin/customs'
    | '/_authenticated/admin/loading-plan'
    | '/_authenticated/admin/managers'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/qa'
    | '/_authenticated/admin/suppliers'
    | '/_authenticated/admin/triggers'
    | '/_authenticated/admin/vacations'
    | '/_authenticated/dashboard/admin'
    | '/_authenticated/dashboard/branch'
    | '/_authenticated/dashboard/manager'
    | '/_authenticated/dashboard/super-admin'
    | '/_authenticated/distribution/$shipmentId'
    | '/_authenticated/shipments/$id'
    | '/_authenticated/shipments/new'
    | '/_authenticated/super-admin/logs'
    | '/_authenticated/super-admin/users'
    | '/_authenticated/admin/'
    | '/_authenticated/shipments/'
    | '/_authenticated/super-admin/'
    | '/_authenticated/shipments/$id/products'
    | '/api/public/hooks/refresh-fx'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicHooksRefreshFxRoute: typeof ApiPublicHooksRefreshFxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transfers': {
      id: '/_authenticated/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AuthenticatedTransfersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin': {
      id: '/_authenticated/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof AuthenticatedSuperAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/statistics': {
      id: '/_authenticated/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof AuthenticatedStatisticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/offers': {
      id: '/_authenticated/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AuthenticatedOffersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master-data': {
      id: '/_authenticated/master-data'
      path: '/master-data'
      fullPath: '/master-data'
      preLoaderRoute: typeof AuthenticatedMasterDataRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager-offers': {
      id: '/_authenticated/manager-offers'
      path: '/manager-offers'
      fullPath: '/manager-offers'
      preLoaderRoute: typeof AuthenticatedManagerOffersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/distribution': {
      id: '/_authenticated/distribution'
      path: '/distribution'
      fullPath: '/distribution'
      preLoaderRoute: typeof AuthenticatedDistributionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/costs': {
      id: '/_authenticated/costs'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof AuthenticatedCostsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/branch-requests': {
      id: '/_authenticated/branch-requests'
      path: '/branch-requests'
      fullPath: '/branch-requests'
      preLoaderRoute: typeof AuthenticatedBranchRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/branch-offers': {
      id: '/_authenticated/branch-offers'
      path: '/branch-offers'
      fullPath: '/branch-offers'
      preLoaderRoute: typeof AuthenticatedBranchOffersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/branch-calendar': {
      id: '/_authenticated/branch-calendar'
      path: '/branch-calendar'
      fullPath: '/branch-calendar'
      preLoaderRoute: typeof AuthenticatedBranchCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin/': {
      id: '/_authenticated/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof AuthenticatedSuperAdminIndexRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/shipments/': {
      id: '/_authenticated/shipments/'
      path: '/shipments'
      fullPath: '/shipments/'
      preLoaderRoute: typeof AuthenticatedShipmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/super-admin/users': {
      id: '/_authenticated/super-admin/users'
      path: '/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof AuthenticatedSuperAdminUsersRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/logs': {
      id: '/_authenticated/super-admin/logs'
      path: '/logs'
      fullPath: '/super-admin/logs'
      preLoaderRoute: typeof AuthenticatedSuperAdminLogsRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/shipments/new': {
      id: '/_authenticated/shipments/new'
      path: '/shipments/new'
      fullPath: '/shipments/new'
      preLoaderRoute: typeof AuthenticatedShipmentsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shipments/$id': {
      id: '/_authenticated/shipments/$id'
      path: '/shipments/$id'
      fullPath: '/shipments/$id'
      preLoaderRoute: typeof AuthenticatedShipmentsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/distribution/$shipmentId': {
      id: '/_authenticated/distribution/$shipmentId'
      path: '/$shipmentId'
      fullPath: '/distribution/$shipmentId'
      preLoaderRoute: typeof AuthenticatedDistributionShipmentIdRouteImport
      parentRoute: typeof AuthenticatedDistributionRoute
    }
    '/_authenticated/dashboard/super-admin': {
      id: '/_authenticated/dashboard/super-admin'
      path: '/dashboard/super-admin'
      fullPath: '/dashboard/super-admin'
      preLoaderRoute: typeof AuthenticatedDashboardSuperAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/manager': {
      id: '/_authenticated/dashboard/manager'
      path: '/dashboard/manager'
      fullPath: '/dashboard/manager'
      preLoaderRoute: typeof AuthenticatedDashboardManagerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/branch': {
      id: '/_authenticated/dashboard/branch'
      path: '/dashboard/branch'
      fullPath: '/dashboard/branch'
      preLoaderRoute: typeof AuthenticatedDashboardBranchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/admin': {
      id: '/_authenticated/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AuthenticatedDashboardAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/vacations': {
      id: '/_authenticated/admin/vacations'
      path: '/vacations'
      fullPath: '/admin/vacations'
      preLoaderRoute: typeof AuthenticatedAdminVacationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/triggers': {
      id: '/_authenticated/admin/triggers'
      path: '/triggers'
      fullPath: '/admin/triggers'
      preLoaderRoute: typeof AuthenticatedAdminTriggersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/suppliers': {
      id: '/_authenticated/admin/suppliers'
      path: '/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AuthenticatedAdminSuppliersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/qa': {
      id: '/_authenticated/admin/qa'
      path: '/qa'
      fullPath: '/admin/qa'
      preLoaderRoute: typeof AuthenticatedAdminQaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/managers': {
      id: '/_authenticated/admin/managers'
      path: '/managers'
      fullPath: '/admin/managers'
      preLoaderRoute: typeof AuthenticatedAdminManagersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/loading-plan': {
      id: '/_authenticated/admin/loading-plan'
      path: '/loading-plan'
      fullPath: '/admin/loading-plan'
      preLoaderRoute: typeof AuthenticatedAdminLoadingPlanRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customs': {
      id: '/_authenticated/admin/customs'
      path: '/customs'
      fullPath: '/admin/customs'
      preLoaderRoute: typeof AuthenticatedAdminCustomsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/countries-master': {
      id: '/_authenticated/admin/countries-master'
      path: '/countries-master'
      fullPath: '/admin/countries-master'
      preLoaderRoute: typeof AuthenticatedAdminCountriesMasterRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/countries': {
      id: '/_authenticated/admin/countries'
      path: '/countries'
      fullPath: '/admin/countries'
      preLoaderRoute: typeof AuthenticatedAdminCountriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/branches': {
      id: '/_authenticated/admin/branches'
      path: '/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AuthenticatedAdminBranchesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/hooks/refresh-fx': {
      id: '/api/public/hooks/refresh-fx'
      path: '/api/public/hooks/refresh-fx'
      fullPath: '/api/public/hooks/refresh-fx'
      preLoaderRoute: typeof ApiPublicHooksRefreshFxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/shipments/$id/products': {
      id: '/_authenticated/shipments/$id/products'
      path: '/products'
      fullPath: '/shipments/$id/products'
      preLoaderRoute: typeof AuthenticatedShipmentsIdProductsRouteImport
      parentRoute: typeof AuthenticatedShipmentsIdRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBranchesRoute: typeof AuthenticatedAdminBranchesRoute
  AuthenticatedAdminCountriesRoute: typeof AuthenticatedAdminCountriesRoute
  AuthenticatedAdminCountriesMasterRoute: typeof AuthenticatedAdminCountriesMasterRoute
  AuthenticatedAdminCustomsRoute: typeof AuthenticatedAdminCustomsRoute
  AuthenticatedAdminLoadingPlanRoute: typeof AuthenticatedAdminLoadingPlanRoute
  AuthenticatedAdminManagersRoute: typeof AuthenticatedAdminManagersRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminQaRoute: typeof AuthenticatedAdminQaRoute
  AuthenticatedAdminSuppliersRoute: typeof AuthenticatedAdminSuppliersRoute
  AuthenticatedAdminTriggersRoute: typeof AuthenticatedAdminTriggersRoute
  AuthenticatedAdminVacationsRoute: typeof AuthenticatedAdminVacationsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBranchesRoute: AuthenticatedAdminBranchesRoute,
  AuthenticatedAdminCountriesRoute: AuthenticatedAdminCountriesRoute,
  AuthenticatedAdminCountriesMasterRoute:
    AuthenticatedAdminCountriesMasterRoute,
  AuthenticatedAdminCustomsRoute: AuthenticatedAdminCustomsRoute,
  AuthenticatedAdminLoadingPlanRoute: AuthenticatedAdminLoadingPlanRoute,
  AuthenticatedAdminManagersRoute: AuthenticatedAdminManagersRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminQaRoute: AuthenticatedAdminQaRoute,
  AuthenticatedAdminSuppliersRoute: AuthenticatedAdminSuppliersRoute,
  AuthenticatedAdminTriggersRoute: AuthenticatedAdminTriggersRoute,
  AuthenticatedAdminVacationsRoute: AuthenticatedAdminVacationsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDistributionRouteChildren {
  AuthenticatedDistributionShipmentIdRoute: typeof AuthenticatedDistributionShipmentIdRoute
}

const AuthenticatedDistributionRouteChildren: AuthenticatedDistributionRouteChildren =
  {
    AuthenticatedDistributionShipmentIdRoute:
      AuthenticatedDistributionShipmentIdRoute,
  }

const AuthenticatedDistributionRouteWithChildren =
  AuthenticatedDistributionRoute._addFileChildren(
    AuthenticatedDistributionRouteChildren,
  )

interface AuthenticatedSuperAdminRouteChildren {
  AuthenticatedSuperAdminLogsRoute: typeof AuthenticatedSuperAdminLogsRoute
  AuthenticatedSuperAdminUsersRoute: typeof AuthenticatedSuperAdminUsersRoute
  AuthenticatedSuperAdminIndexRoute: typeof AuthenticatedSuperAdminIndexRoute
}

const AuthenticatedSuperAdminRouteChildren: AuthenticatedSuperAdminRouteChildren =
  {
    AuthenticatedSuperAdminLogsRoute: AuthenticatedSuperAdminLogsRoute,
    AuthenticatedSuperAdminUsersRoute: AuthenticatedSuperAdminUsersRoute,
    AuthenticatedSuperAdminIndexRoute: AuthenticatedSuperAdminIndexRoute,
  }

const AuthenticatedSuperAdminRouteWithChildren =
  AuthenticatedSuperAdminRoute._addFileChildren(
    AuthenticatedSuperAdminRouteChildren,
  )

interface AuthenticatedShipmentsIdRouteChildren {
  AuthenticatedShipmentsIdProductsRoute: typeof AuthenticatedShipmentsIdProductsRoute
}

const AuthenticatedShipmentsIdRouteChildren: AuthenticatedShipmentsIdRouteChildren =
  {
    AuthenticatedShipmentsIdProductsRoute:
      AuthenticatedShipmentsIdProductsRoute,
  }

const AuthenticatedShipmentsIdRouteWithChildren =
  AuthenticatedShipmentsIdRoute._addFileChildren(
    AuthenticatedShipmentsIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBranchCalendarRoute: typeof AuthenticatedBranchCalendarRoute
  AuthenticatedBranchOffersRoute: typeof AuthenticatedBranchOffersRoute
  AuthenticatedBranchRequestsRoute: typeof AuthenticatedBranchRequestsRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCostsRoute: typeof AuthenticatedCostsRoute
  AuthenticatedDistributionRoute: typeof AuthenticatedDistributionRouteWithChildren
  AuthenticatedManagerOffersRoute: typeof AuthenticatedManagerOffersRoute
  AuthenticatedMasterDataRoute: typeof AuthenticatedMasterDataRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOffersRoute: typeof AuthenticatedOffersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStatisticsRoute: typeof AuthenticatedStatisticsRoute
  AuthenticatedSuperAdminRoute: typeof AuthenticatedSuperAdminRouteWithChildren
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
  AuthenticatedTransfersRoute: typeof AuthenticatedTransfersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDashboardAdminRoute: typeof AuthenticatedDashboardAdminRoute
  AuthenticatedDashboardBranchRoute: typeof AuthenticatedDashboardBranchRoute
  AuthenticatedDashboardManagerRoute: typeof AuthenticatedDashboardManagerRoute
  AuthenticatedDashboardSuperAdminRoute: typeof AuthenticatedDashboardSuperAdminRoute
  AuthenticatedShipmentsIdRoute: typeof AuthenticatedShipmentsIdRouteWithChildren
  AuthenticatedShipmentsNewRoute: typeof AuthenticatedShipmentsNewRoute
  AuthenticatedShipmentsIndexRoute: typeof AuthenticatedShipmentsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBranchCalendarRoute: AuthenticatedBranchCalendarRoute,
  AuthenticatedBranchOffersRoute: AuthenticatedBranchOffersRoute,
  AuthenticatedBranchRequestsRoute: AuthenticatedBranchRequestsRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCostsRoute: AuthenticatedCostsRoute,
  AuthenticatedDistributionRoute: AuthenticatedDistributionRouteWithChildren,
  AuthenticatedManagerOffersRoute: AuthenticatedManagerOffersRoute,
  AuthenticatedMasterDataRoute: AuthenticatedMasterDataRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOffersRoute: AuthenticatedOffersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStatisticsRoute: AuthenticatedStatisticsRoute,
  AuthenticatedSuperAdminRoute: AuthenticatedSuperAdminRouteWithChildren,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
  AuthenticatedTransfersRoute: AuthenticatedTransfersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDashboardAdminRoute: AuthenticatedDashboardAdminRoute,
  AuthenticatedDashboardBranchRoute: AuthenticatedDashboardBranchRoute,
  AuthenticatedDashboardManagerRoute: AuthenticatedDashboardManagerRoute,
  AuthenticatedDashboardSuperAdminRoute: AuthenticatedDashboardSuperAdminRoute,
  AuthenticatedShipmentsIdRoute: AuthenticatedShipmentsIdRouteWithChildren,
  AuthenticatedShipmentsNewRoute: AuthenticatedShipmentsNewRoute,
  AuthenticatedShipmentsIndexRoute: AuthenticatedShipmentsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicHooksRefreshFxRoute: ApiPublicHooksRefreshFxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
